complete:
    fail: Process Completed - Failure
    success: Process Completed - Success
conctact:
    name: Audit Management System
contact:
    email: ams@gmail.com
    web: ams.com
feign:
    exp: Feign  Exception Caught
    'null': Feign Proxy returned Null Object
    proxy:
        exp: Feign Proxy Exception Caught
fos:
    auth: http://localhost:9400/
logging:
    level:
        org:
            hibernate:
                stat: debug
            springframework:
                context: DEBUG
                web: DEBUG
server:
    port: 9300
spring:
    application:
        name: auditBenchmark
string:
    end: End
    invalid:
        cred: Invalid Credentials
    main:
        package: com.cts.benchmark
    'null': Oops! Something went wrong
    null.exception: Array out of bounds
    req: 'Request{}:'
    start: Start
    swagg:
        desc: Benchmark Service return the list of Internal and SOX audit type together
            with acceptable number of NO answers.
        help: Help
        lic: Audit 1.0
        title: Benchmark Service Documentation
        ver: 1.0
    token: 'Token{}:'
    token.exp: Token Expired! login again
    valfail: Validation Failed
valcheck:
    fail: End checkTokenValidity fail
    success: End checkTokenValidity success
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
